server:
  port: 8082

spring:
  application:
    name: edge-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: world-route
          uri: http://localhost:8084
          predicates:
            - Path=/world/**
        - id: greeting-route
          uri: http://localhost:8085
          predicates:
            - Path=/greet/**
        - id: graphql-route
          uri: http://localhost:8083
          predicates:
            - Path=/graphql/**
            - Method=POST
          filters:
            - RewritePath=/graphql/(?<remaining>.*), /${remaining}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7081/realms/myrealm

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,bus-refresh
